### ISSUE TITLE
fastlane issues

### ISSUE THREAD

**Issue by IzzySoft** [jakubvalenta/geoshare#1]
graphics in your fastlane are in the wrong place, they need to go into an `images` subdirectory (see the [IzzyOnDroid Fastlane Documentation](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) for details).

**Comment by jakubvalenta** [comment]
Thanks for your review. I've moved the images accordingly in bd57fdb.

**Comment by IzzySoft** [comment]
Thanks! GeoShare will [show up here](https://apt.izzysoft.de/packages/page.ooooo.geoshare) with the next sync around 7 pm UTC, and it's a [Reproducible Build](https://reproducible-builds.org/) so the "green shield" will be up :partying_face: Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme. Fastlane is active here, so changes to it will be pulled along with future releases.

**Comment by IzzySoft** [comment]
Glad you like it! :star_struck: Looking forward to the basge showing up then :wink:
