### ISSUE TITLE
Allow copying to clipboard an sharing to other types of apps

### ISSUE THREAD

**Issue by bovergaauw** [jakubvalenta/geoshare#11]
Geo share would be even more useful if it allowed copying the geo: link to the clipboard or sharing it directly to other apps such as SMS, Signal, WhatsApp, etc. for sending it to others.

**Comment by jakubvalenta** [comment]
Great idea!

**Comment by KiritoStorm** [comment]
Yeah I also thought about this, also good when sharing is not working (for some reason) like in my case. 👍

**Comment by jakubvalenta** [comment]
Implemented in v1.5.0. It should be available in F-Droid in 3 to 6 days.

When sharing a Google Maps link, you should now see two options: "Copy geo: link" and "Share geo: link". Depending on the Android version and the particular share menu, the two options are displayed either as two Geo Share icons or as one icon with a dropdown menu and a dialog:

![1-540](https://github.com/user-attachments/assets/d407630d-323f-4f5a-8464-29985de812b1)
