### ISSUE TITLE
F-Droid says you "communicate with Google"

### ISSUE THREAD

**Issue by michaelblyons** [jakubvalenta/geoshare#12]
Hi there. On F-Droid, there's an "anti-feature" listed wherein they seem to imply that this app communicates with Google to decode links. Can you write a little here and/or in the ReadMe about what that means?

Context: I had imagined using this app to translate GMaps links sent to me in SMS or Email into ones I could use for my non-Google maps apps. But if you talk to Google to do so, it's not as enticing a prospect.

**Comment by michaelblyons** [comment]
Thanks! That's very clear, yes.

**Comment by jakubvalenta** [comment]
Fixed in v1.5.0. It should be available in F-Droid in 3 to 6 days.

The information has been added to the F-Droid description, README and on a new FAQ screen in the app.
