### ISSUE TITLE
Send placename search to local app

### ISSUE THREAD

**Issue by michaelblyons** [jakubvalenta/geoshare#15]
This may not be possible (and worse, may result in false positives), but I was wondering if the non-minified place name links could be sent directly to a local map app to look up, rather than getting coordinates from Google. (The second exame from your reply to #12.)

Obviously, some apps that support geo coordinates do not support search. Furthermore I do not know how intents work for something like this.

But it could be something to investigate later.

**Comment by michaelblyons** [comment]
Correct, it is the second one that I wanted. The `q=` mode in OsmAnd sounds good, and an option for offline mode would be great! (Someday 😉)

**Comment by jakubvalenta** [comment]
Cool, I'll comment here when I have an update regarding the feature.

**Comment by jakubvalenta** [comment]
Implemented in v2.0.0. It will be available on F-Droid in 3 to 6 days.

Geo Share now asks the user before connecting to Google using a dialog window.

1. If the link is a short link, then the options are Allow [connecting to Google] or Quit.

    ![2-540](https://github.com/user-attachments/assets/130c200f-6dcd-4bf9-b656-aa868be52be7)

2. If the link isn't a short link but it doesn't contain coordinates, then the options are Allow [connecting to Google] or Create a search geo: link, as suggested in this issue.

    ![5-540](https://github.com/user-attachments/assets/90b18d98-cb02-49f4-92b9-0000e5d65d76)

If the user toogles "Don't ask me again", then the dialog will not appear again. The user can then change this preference on the app's new Preferences screen.

**Comment by michaelblyons** [comment]
This looks great!
