### ISSUE TITLE
Add support for links to Google Search results

### ISSUE THREAD

**Issue by Norbert80** [jakubvalenta/geoshare#17]
### Motivation

https://g.co/kgs/91UYXud

### Suggestion

.

**Comment by jakubvalenta** [comment]
Thanks for the report! I'll get to it shortly.

Note to self: The link leads to a Google Search results page, which doesn't contain geographical coordinates, but there is a street address link, which leads to Google Maps, so Geo Share could follow that link and then standard Google Maps URL or HTML parsing would apply.

![screenshot_2024-12-14_17-27-16-e](https://github.com/user-attachments/assets/f59ae6ee-b7f1-42d9-b899-8b336ea1e7d7)

**Comment by jakubvalenta** [comment]
Implemented in v2.0.0. It will be available on F-Droid in 3 to 6 days.
