### ISSUE TITLE
Themed Monochrome Adaptive Icon

### ISSUE THREAD

**Issue by NielSync** [jakubvalenta/geoshare#3]
![Screenshot_20241108-233350_1.jpg](https://github.com/user-attachments/assets/9ec34702-8156-4a60-ae8f-86d1fd30c28d)

**Comment by jakubvalenta** [comment]
Thanks for the report. The issue has been fixed in 6c141c6a0665082e7550d1ab00ddcdcf8483ce83 and released as [v1.1.1](https://github.com/jakubvalenta/geoshare/releases/tag/v1.1.1).
